# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7a75db98a58d88bd7bf099ec7b458cfa509674b7bd20145b328cb926da1510e33e228042cd63936abf400adc2809d90219798fd5459101965099a9bcbe01f72e

test:
  secret_key_base: 2e7bf26029c8690439519d3f27bd4fdbe9c54b8dbc2cc9ebbe7bcfb5ee07c9053908c1f4edc4d8add5704c50272e3fd0c1b48408343a9e796027fa45767848b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
